### ISSUE TITLE
How long does the run_texture_optimization.lua takes to run??

### ISSUE THREAD

**Issue by DixithR19** [leehomyc/Faster-High-Res-Neural-Inpainting#16]
When I try to run the run_texture_optimization.lua, it repeats the same thing over and over again. It say synthesis finished at resolution 3 and repeats itself. How do I know when to stop the program.

Thank you.

**Comment by leehomyc** [comment]
It should only takes 3 iterations and it will stop. Did you check the synthesis result? Is it running multiple images?

**Comment by DixithR19** [comment]
I am not sure about that. How do we check the synthesis results? Since I am running it on a server.

Thank you.

**Comment by leehomyc** [comment]
Check the file transfer_CNNMRF_wrapper.lua. In line 574:

params.output_folder = string.format('examples/%s',params.save_name)
params.save_name=save_name.."_"..style_name.."TO"..content_name

so the synthesized images should be saved under examples/demo_...TO.../

**Comment by DixithR19** [comment]
Thank you, the issue has been resolved. As the results generated are for the example images, what changes should I make to the code, so that I can run for my own image and mask.

Thank you.

**Comment by hacql2004** [comment]
@DixithR19  have the same question with you.  I also want to modify the code to make it suit for my own mask, and I'm still not sure should just modify the texture loss is enough?

**Comment by leehomyc** [comment]
You need to have initialization which could be anything (in our paper from the content network).

**Comment by leehomyc** [comment]
We accelerated the algorithm now it only takes 30s to run.
